### PR TITLE
added standard and switched to this coding style

### PR DESCRIPTION
**Pull request by gausby**

### CODE REVIEW

**Comment by mafintosh** [comment]
-1 to .editorconfig. Otherwise LGTM

**Comment by gausby** [comment]
What's not to like about .editorconfig?

...it makes my editor work when I switch between all these different js coding styles.

**Comment by mafintosh** [comment]
Solve it locally. I don't like dot-files in the repo except for .gitignore

**Comment by gausby** [comment]
Okay, I'll see if I can make it a non-hidden file and make editorconfig accept that.

**Pull request merged**
